package main

type Book struct {
  Title, CoverImage string
}

var Books = []Book{
  {`V for Vendetta`, `v-for-vendetta.jpg`},
  {`Paper Girls`, `paper-girls.jpg`},
  {`Saga`, `saga.jpg`},
  {`Brother Ray`, `brother-ray.jpg`},
  {`Galápagos`, `galapagos.jpg`},
  {`One Hundred Years of Solitude`, `one-hundred-years-of-solitude.jpeg`},
  {`Ender's Game`, `ender.jpg`},
  {`White Fang`, `white-fang.jpg`},
  {`Around the World in 80 Days`, `around-the-world-in-80-days.jpg`},
  {`Breakfast of Champions`, `breakfast-of-champions.jpg`},
  {`Dr. Jekyll and Mr. Hyde`, `dr-jekyll-and-mr-hyde.jpg`},
  {`The Importance of Being Ernest`, `importance-of-being-earnest.jpg`},
  {`Dracula`, `dracula-2.jpg`},
  {`The Book Thief`, `the-book-thief.jpg`},
  {`Tuesdays with Morrie`, `tuesdays-with-morrie.jpg`},
  {`What Happy People Know`, `what-happy-people-know.jpg`},
  {`Water for Elephants`, `water-for-elephants.jpg`},
  {`Shadow of the Wind`, `shadow-of-the-wind.jpg`},
  {`Gone Girl`, `gone-girl.jpg`},
  {`Call of the Wild`, `The_Call_of_the_Wild.jpg`},
  {`Heart of Darkness`, `heart-of-darkness.jpg`},
  {`Gulliver’s Travels`, `gullivers_travels.jpg`},
  {`A Song of Ice and Fire series`, `A_Song_of_Ice_and_Fire.jpg`},
  {`The Hobbit`, `the-hobbit.jpg`},
  {`Lord of the Rings`, `lord_of_the_rings.jpg`},
  {`The Lion, the Witch, and the Wardrobe`, `LionWardrobe13.jpg`},
  {`The Hunger Games series`, `the-hunger-games-trilogy.jpg`},
  {`Sherlock Holmes`, `sherlock-holmes.jpg`},
  {`Siddhartha`, `siddhartha.jpeg`},
  {`Demian`, `demian.jpg`},
  {`The Hitchhiker’s Guide to the Galaxy series`, `HHGG-Complete.jpg`},
  {`Neuromancer`, `neuromancer.jpg`},
  {`Everything is Illuminated`, `Everything-is-Illuminated.jpg`},
  {`The Fault in Our Stars`, `The_Fault_in_Our_Stars.jpg`},
  {`The Count of Monte Cristo`, `count-of-monte-cristo.jpg`},
  {`The Grapes of Wrath`, `grapes-of-wrath.jpg`},
  {`Cannery Row`, `cannery-row.jpg`},
  {`Sweet Tuesday`, `sweet-thursday.jpg`},
  {`The Road`, `the-road.jpg`},
  {`The Curious Incident of the Dog in the Nighttime`, `curious-incident.jpg`},
  {`The Catcher in the Rye`, `Catcher-in-the-rye.jpg`},
  {`Angels and Demons`, `AngelsAndDemons.jpg`},
  {`Howl and other poems`, `Howl-Cover.jpg`},
  {`One Flew Over the Cuckcoo’s Nest`, `one-flew-over.jpg`},
  {`Brave New World`, `Brave-New-World.jpg`},
  {`Romeo and Juliet`, `romeo-and-juliet.jpg`},
  {`To Kill a Mockingbird`, `to-kill-a-mocking-bird.jpg`},
  {`Dante's Inferno`, `inferno.jpg`},
  {`The Great Gatsby`, `gatsby-original-cover-art.jpg`},
  {`Into the Wild`, `into-the-wild.jpg`},
}
