package main

type Pub struct {
  Title,
  Author,
  Journal,
  Volume,
  BookTitle,
  Organization,
  Number,
  Pages,
  Year,
  Publisher,
  URL string
}

var Pubs = []Pub{
  {
    Title: "Interactions of Nitrosomonas europaea and Nitrobacter winogradskyi grown in co-culture",
    Author: "Pèrez, Josè and Buchanan, Alex and Mellbye, Brett and Ferrell, Rebecca and Chang, Jeffrey H and Chaplen, Frank and Bottomley, Peter J and Arp, Daniel J and Sayavedra-Soto, Luis A",
    Journal: "Archives of microbiology",
    Volume: "197",
    Number: "1",
    Pages: "79--89",
    Year: "2015",
    Publisher: "Springer",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:u-x6o8ySG0sC",
  },
  {
    Title: "Nitrobacter winogradskyi transcriptomic response to low and high ammonium concentrations",
    Author: "Sayavedra-Soto, Luis and Ferrell, Rebecca and Dobie, Michael and Mellbye, Brett and Chaplen, Frank and Buchanan, Alex and Chang, Jeffrey and Bottomley, Peter and Arp, Daniel",
    Journal: "FEMS microbiology letters",
    Volume: "362",
    Number: "3",
    Pages: "1--7",
    Year: "2015",
    Publisher: "The Oxford University Press",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:d1gkVwhDpl0C",
  },
  {
    Title: "Using next-generation sequencing to determine the influence of metabolic intermediates on the Pseudomonas protegens transcriptome.",
    Author: "Clifford, J and Kidarsa, T and Buchanan, A and Chang, JH and Loper, J",
    BookTitle: "PHYTOPATHOLOGY",
    Volume: "103",
    Number: "6",
    Pages: "28--28",
    Year: "2013",
    Organization: "AMER PHYTOPATHOLOGICAL SOC 3340 PILOT KNOB ROAD, ST PAUL, MN 55121 USA",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:2osOgNQ5qMEC",
  },
  {
    Title: "Phloroglucinol functions as an intracellular and intercellular chemical messenger influencing gene expression in Pseudomonas protegens",
    Author: "Clifford, Jennifer C and Buchanan, Alex and Vining, Oliver and Kidarsa, Teresa A and Chang, Jeff H and McPhail, Kerry L and Loper, Joyce E",
    Journal: "Environmental microbiology",
    Year: "2015",
    Publisher: "Wiley Online Library",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:qjMakFHDy7sC",
  },
  {
    Title: "Effects of sulforaphane and 3, 3′-diindolylmethane on genome-wide promoter methylation in normal prostate epithelial cells and prostate cancer cells",
    Author: "Wong, Carmen P and Hsu, Anna and Buchanan, Alex and Palomera-Sanchez, Zoraya and Beaver, Laura M and Houseman, E Andres and Williams, David E and Dashwood, Roderick H and Ho, Emily",
    Journal: "PloS one",
    Volume: "9",
    Number: "1",
    Pages: "e86787",
    Year: "2014",
    Publisher: "Public Library of Science",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:u5HHmVD_uO8C",
  },
  {
    Title: "Sulforaphane alters the expression of long intragenic non-coding RNAs that are dysregulated in prostate cancer cells (644.10)",
    Author: "Beaver, Laura and Buchanan, Alex and Sokolowski, Elizabeth and Glasser, Sarah and Wong, Carmen and Chang, Jeff and Williams, David and Dashwood, Roderick and Ho, Emily",
    Journal: "The FASEB Journal",
    Volume: "28",
    Number: "1 Supplement",
    Pages: "644--10",
    Year: "2014",
    Publisher: "FASEB",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:zYLM7Y9cAGgC",
  },
  {
    Title: "Transcriptome analysis reveals a dynamic and differential transcriptional response to sulforaphane in normal and prostate cancer cells and suggests a role for Sp1 in chemoprevention",
    Author: "Beaver, Laura M and Buchanan, Alex and Sokolowski, Elizabeth I and Riscoe, Allison N and Wong, Carmen P and Chang, Jeff H and Löhr, Christiane V and Williams, David E and Dashwood, Roderick H and Ho, Emily",
    Journal: "Molecular nutrition & food research",
    Volume: "58",
    Number: "10",
    Pages: "2001--2013",
    Year: "2014",
    Publisher: "Wiley Online Library",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:9yKSN-GCB0IC",
  },
  {
    Title: "Genome-wide transcriptome analysis of the effects of sulforphane on normal and prostate cancer cells",
    Author: "Beaver, Laura Michelle and Buchanan, Alex and Sokolowski, Elizabeth I and Chang, Jeff H and Wong, Carmen P and Williams, David E and Dashwood, Roderick H and Ho, Emily",
    Journal: "The FASEB Journal",
    Volume: "27",
    Number: "1MeetingAbstracts",
    Pages: "248--2",
    Year: "2013",
    Publisher: "FASEB",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:UeHWp8X0CEIC",
  },
  {
    Title: "RNA-Seq analysis of resistant and susceptible potato varieties during the early stages of potato virus Y infection",
    Author: "Goyer, Aymeric and Hamlin, Launa and Crosslin, James M and Buchanan, Alex and Chang, Jeff H",
    Journal: "BMC genomics",
    Volume: "16",
    Number: "1",
    Pages: "1",
    Year: "2015",
    Publisher: "BioMed Central",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:IjCSPb-OGe4C",
  },
  {
    Title: "Alternative Splicing in the Obligate Biotrophic Oomycete Pathogen Pseudoperonospora cubensis",
    Author: "Burkhardt, Alyssa and Buchanan, Alex and Cumbie, Jason S and Savory, Elizabeth A and Chang, Jeff H and Day, Brad",
    Journal: "Molecular Plant-Microbe Interactions",
    Volume: "28",
    Number: "3",
    Pages: "298--309",
    Year: "2015",
    Publisher: "Am Phytopath Society",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:Y0pCki6q_DkC",
  },
  {
    Title: "Constraints-based modeling of the nitrifying bacteria Nitrosomonas europaea and Nitrobacter hamburgensis",
    Author: "Chaplen, Frank WR and Buchanan, Alex and Chang, Jeff H and Sayavedra-Soto, Luis",
    BookTitle: "ABSTRACTS OF PAPERS OF THE AMERICAN CHEMICAL SOCIETY",
    Volume: "245",
    Year: "2013",
    Organization: "AMER CHEMICAL SOC 1155 16TH ST, NW, WASHINGTON, DC 20036 USA",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:Tyk-4Ss8FVUC",
  },
  {
    Title: "Elucidating the coupled dynamics of the nitrifying bacteria Nitrosomonas europaea and Nitrobacter winogradskyi grown in chemostat co-culture",
    Author: "Chaplen, Frank WR and Perez, Jose and Bottomley, Peter and Buchanan, Alex and Murthy, Ganti S and Chang, Jeff H and Sayavedra-Soto, Luis A",
    BookTitle: "ABSTRACTS OF PAPERS OF THE AMERICAN CHEMICAL SOCIETY",
    Volume: "247",
    Year: "2014",
    Organization: "AMER CHEMICAL SOC 1155 16TH ST, NW, WASHINGTON, DC 20036 USA",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:W7OEmFMy1HYC",
  },
  {
    Title: "Model integration for elucidating the coupled environmental dynamics of the nitrifying bacteria Nitrosomonas europaea and Nitrobacter winogradskyi",
    Author: "Chaplen, Frank WR and Perez, Jose and Bottomley, Peter and Buchanan, Alex and Murthy, Ganti S and Chang, Jeff H and Sayavedra-Soto, Luis A",
    BookTitle: "ABSTRACTS OF PAPERS OF THE AMERICAN CHEMICAL SOCIETY",
    Volume: "247",
    Year: "2014",
    Organization: "AMER CHEMICAL SOC 1155 16TH ST, NW, WASHINGTON, DC 20036 USA",
    URL: "https://scholar.google.com.au/citations?view_op=view_citation&hl=en&user=C4C2QrgAAAAJ&citation_for_view=C4C2QrgAAAAJ:YsMSGLbcyi4C",
  },
}
